name: Dispatching Workflow

on:
  pull_request:
  workflow_dispatch:
    inputs:
      some_string:
        description: 'Some random string'
        required: true
        type: string
        default: "example"


jobs:
  Test_Things:
    runs-on: ubuntu-latest
    steps:
      - name: Dump text for baseline
        run: |
          echo "This will dump the text for baseline"

      - name: Determine Github Action
        id: get_action
        run: |
          echo "PR number: ${{ github.event.pull_request.number }}"
          echo "Event action: ${{ github.event.action }}"
          echo "PR head SHA: ${{ github.event.pull_request.head.sha }}"
          echo "Workflow run ID: ${{ github.run_id }}"
          echo "Run attempt: ${{ github.run_attempt }}"

          if [ "${{ github.event.action }}" = "opened" ]; then
            echo "Initial PR workflow cycle"
            echo "value=opened" >> $GITHUB_OUTPUT
          elif [ "${{ github.event.action }}" = "synchronize" ]; then
            echo "Workflow triggered by a subsequent commit"
            echo "value=synchronize" >> $GITHUB_OUTPUT
          elif [ "${{ github.event.action }}" = "reopened" ]; then
            echo "PR reopened"
            echo "value=reopened" >> $GITHUB_OUTPUT
          fi

      - name: Checkout repo-B
        uses: actions/checkout@v4
        with:
          repository: kjohnsonhpe/repo-B

      - name: Call Action
        uses: ./repo-B/actions/get-action
        with:
          input: ${{ steps.get_action.outputs.value }}
